services:
  api:
    restart: unless-stopped
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-heroes}
      API_PORT: ${API_PORT:-3000}
    depends_on:
      - postgres
  postgres:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-heroes}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
