name: Deploy image to kubernetes
on:
  workflow_run:
    workflows: ["Build container image"]
    branches: [main]
    types: [completed]
jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:
      group: k8s-examples
    steps:
      - name: update the pods
        run: |
          CHANGE_CAUSE=$(date '+%s')
          export DEPLOY_PATCH="{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"kubernetes.io/change-cause\":\"$CHANGE_CAUSE\"},\"labels\":{\"build\":\"$GITHUB_SHA\"}}}}}"
          kubectl -n default patch deployment api -p "$DEPLOY_PATCH"
